spring:
  cloud:
    stream:
      bindings:
        createEvent:
          destination: yoke-create-event
          producer:
            partition-count: 3
        deleteEvent:
          destination: yoke-delete-event
          producer:
            partition-count: 3

      kafka:
        binder:
          brokers: localhost:9092
          autoAddPartitions: true
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: "{cipher}AQCMxzDAPIsW2aQq24fmyKA2PfU/FbjDYwpc3z8OA/YvX8SiCdXV161dnx1L/ICcE6f4cHYOaGDsPvCwp/nv20NOujRkF2U0pQfE4wp5jeeGO324uNgZeVaIJCHuWHGMaRuUzuXhJdICGFVrVMIp5I5Lj/4XNHdihDWxX1gG9flLu/sr9WXMkUdfKb7t3gSbGFCe84RxUYOnUX4wbGAI/zMbdOzC6nZoYoIKzjAahfwV2PnNvnWt8QF1vqcknw3s4YadMDOtc3PcAcuV31Ns87UX77pN/FzBSaVtpPtpwp9TcdxuE8v87OoYjk3cFX5epKtDHJqHnz4LvypWRHOfICkIt/9xZQMnuDEbYgxBQWtWxWQ9dexyDgXk3xQVKtUowsk="

server:
  port: 8083

yoke:
  notify:
    url: http://yoke-notify/event
