spring:
  datasource:
    url: jdbc:postgresql://yoke-postgres:5432/postgres
    username: postgres
    password: "{cipher}AQCMxzDAPIsW2aQq24fmyKA2PfU/FbjDYwpc3z8OA/YvX8SiCdXV161dnx1L/ICcE6f4cHYOaGDsPvCwp/nv20NOujRkF2U0pQfE4wp5jeeGO324uNgZeVaIJCHuWHGMaRuUzuXhJdICGFVrVMIp5I5Lj/4XNHdihDWxX1gG9flLu/sr9WXMkUdfKb7t3gSbGFCe84RxUYOnUX4wbGAI/zMbdOzC6nZoYoIKzjAahfwV2PnNvnWt8QF1vqcknw3s4YadMDOtc3PcAcuV31Ns87UX77pN/
    FzBSaVtpPtpwp9TcdxuE8v87OoYjk3cFX5epKtDHJqHnz4LvypWRHOfICkIt/9xZQMnuDEbYgxBQWtWxWQ9dexyDgXk3xQVKtUowsk="
  cloud:
    stream:
      kafka:
        binder:
          brokers: yoke-kafka:29092
    config:
      discovery:
        enabled: true
      fail-fast: true
      retry:
       initial-interval: 10000
       multiplier: 1.5
       max-attempts: 20
       max-interval: 15000

    zipkin:
      baseUrl: http://yoke-zipkin:9411   
eureka:
  client:
    serviceUrl:
      defaultZone: http://yoke-eureka-server:8761/eureka

logback:
  destination:
    url: logstash
    port: 5000